### ISSUE TITLE
progress indicator out of max value

### ISSUE THREAD

**Issue by ershat-dl** [Sorbh/kdGaugeViewFlutter#2]
I think you do it well, I really like it. but there are some issues.
1. when speed > max value
2. min or max value with fractionDigits not very nice
3. _optinal_: maybe  it's pretty nice that `activeGaugeColor` could have gradient color
 ![image](https://user-images.githubusercontent.com/79347883/126730400-38bc9378-4d14-4332-ad08-ad926e403f9e.png)

about issue two: I think it's much better that  `minMaxValue`  has another `fractionDigits` ,like `minMaxValuefractionDigits` ...

**Comment by Sorbh** [comment]
Thanks @ershat-dl for reporting this issue. I have added option for activeColorGradinent and limit speed to maxSpeed .

**Comment by ershat-dl** [comment]
Thanks
